### ISSUE TITLE
background-position: center

### ISSUE THREAD

**Issue by Atte** [BTDev/Berrymotes#16]
`background-position: center` results in `ValueError: invalid literal for int() with base 10: 'center'`.

Should probably check for other places where `center` would be valid too.

**Comment by Atte** [comment]
```
Traceback (most recent call last):
  File "/home/berrytube/btprod/berrymotes/emotescraper/bmscraper/emote_processors/abstract_emotes_processor.py", line 36, in run
    self.process_group()
  File "/home/berrytube/btprod/berrymotes/emotescraper/bmscraper/emote_processors/basic_emotes_processor.py", line 49, in process_group
    AbstractEmotesProcessor.process_group(self)
  File "/home/berrytube/btprod/berrymotes/emotescraper/bmscraper/emote_processors/abstract_emotes_processor.py", line 42, in process_group
    self.process_emote(emote)
  File "/home/berrytube/btprod/berrymotes/emotescraper/bmscraper/emote_processors/android_emotes_processor.py", line 147, in process_emote
    cropped = self.extract_single_image(emote, image)
  File "/home/berrytube/btprod/berrymotes/emotescraper/bmscraper/emote_processors/basic_emotes_processor.py", line 83, in extract_single_image
    x = int(emote['background-position'][0].strip('-').strip('px').strip('%'))
```
